# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

dist: trusty
sudo: false

language: cpp
compiler: gcc

script:
  - mkdir build && cd build
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake ..
  - cmake --build .

# For sudo=false builds this section installs the necessary dependencies.
addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-trusty can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - ubuntu-toolchain-r-test
    - debian-sid
    packages:
    - g++-7
    - libboost1.60-all-dev
    - cmake

notifications:
  email: false
