# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

dist: trusty
sudo: false

language: cpp
compiler: gcc

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build && cd build
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake -DCMAKE_CXX_FLAGS="-g -O0 -Wall --coverage" ..
  - cmake --build .
  - ./tests

after_success:
  - coveralls --gcov /usr/bin/gcov-7 --root .. --exclude third_party --exclude source/fmt --exclude source/tiny_obj_loader.h --exclude source/main.cpp -E ".*gtest.*" -E ".*CMakeFiles.*"

# For sudo=false builds this section installs the necessary dependencies.
addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-trusty can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - libboost1.55-all-dev
    - cmake

notifications:
  email: false
